# Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# Uploaded dataset

In [2]:
df= pd.read_csv("D:\priya\internship\IMDB Dataset.csv")

In [3]:
data= df.iloc[:10000]

In [4]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
data['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [6]:
data['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [7]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [8]:
data.duplicated().sum()

17

In [9]:
data.drop_duplicates(inplace=True)

C:\Users\shwet\AppData\Local\Temp\ipykernel_12644\2282015914.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop_duplicates(inplace=True)


In [10]:
data.duplicated().sum()

0

Basic preprocessing
Remove tags
Lowercase
Remove stopwords

In [11]:
import re
def remove_tags(raw_text):
    cleaned_text= re.sub(re.compile('<.*?>'),'', raw_text)
    return cleaned_text

In [12]:
data['review']=data['review'].apply(remove_tags)

C:\Users\shwet\AppData\Local\Temp\ipykernel_12644\3366883445.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review']=data['review'].apply(remove_tags)


In [13]:
data

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [14]:
data['review']= data['review'].apply(lambda x:x.lower())

C:\Users\shwet\AppData\Local\Temp\ipykernel_12644\2096597980.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review']= data['review'].apply(lambda x:x.lower())


In [15]:
data

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[9983 rows x 2 columns]

In [16]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shwet\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
from nltk.corpus import stopwords
sw_list=stopwords.words('english')
data['review']=data['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

C:\Users\shwet\AppData\Local\Temp\ipykernel_12644\1737803637.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review']=data['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [18]:
data


review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [19]:
x= data.iloc[:,0:1]
y=data['sentiment']

In [20]:
x

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [21]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

# Feature Engineering

In [22]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y= encoder.fit_transform(y)

In [23]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=1)

In [54]:
X_train.shape

(7986, 1)

In [55]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1997 entries, 5333 to 2573
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   review  1997 non-null   object
dtypes: object(1)
memory usage: 31.2+ KB


applying BoW

In [56]:
from sklearn.feature_extraction.text import CountVectorizer

In [57]:
cv= CountVectorizer()

In [58]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [59]:
X_train_bow.shape

(7986, 48282)

In [60]:
from sklearn.naive_bayes import GaussianNB
gnb= GaussianNB()
gnb.fit(X_train_bow,y_train)

GaussianNB()

In [61]:
y_pred=gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.6324486730095142

In [63]:
confusion_matrix(y_test, y_pred)

array([[717, 235],
       [499, 546]], dtype=int64)

In [66]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [67]:
rf.fit(X_train_bow, y_train)
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8517776664997496

In [68]:
cv=CountVectorizer(max_features=3000)
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf=rf=RandomForestClassifier()
rf.fit(X_train_bow, y_train)
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8377566349524287

In [69]:
cv=CountVectorizer(ngram_range=(1,3),max_features=5000)
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf=rf=RandomForestClassifier()
rf.fit(X_train_bow, y_train)
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8437656484727091

# Using Tfidf

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review']).toarray()

In [73]:
rf=RandomForestClassifier()

rf.fit(X_train_tfidf, y_train)
y_pred=rf.predict(X_test_tfidf)
accuracy_score(y_test, y_pred)

0.8522784176264396

In [74]:
import gensim

In [80]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shwet\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [81]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [82]:
story=[]
for doc in data['review']:
    raw_sent= sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [84]:
model=gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [85]:
model.build_vocab(story)

In [86]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5876315, 6212140)

In [87]:
len(model.wv.index_to_key)

31845

In [90]:
def document_vector(doc):
    #remove out of vocab words
    doc= [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc],axis=0)

In [91]:
document_vector(df['review'].values[0])

array([-0.20446354,  0.48086828,  0.04406572,  0.17868163, -0.11360488,
       -0.6648532 ,  0.33844563,  1.0647515 , -0.17490748, -0.3658816 ,
       -0.2453849 , -0.5312085 , -0.01779767,  0.22050327, -0.05921424,
       -0.13726705,  0.07167196, -0.2636031 ,  0.0520041 , -0.67296475,
        0.12792939,  0.28691745,  0.32737443, -0.2829517 , -0.3757647 ,
       -0.07819744, -0.3553448 , -0.03684964, -0.484629  ,  0.20674957,
        0.5017143 , -0.07333556,  0.3365158 , -0.3449094 , -0.23993956,
        0.48830262,  0.10382417, -0.55608785, -0.32816786, -0.907156  ,
        0.08772528, -0.3460025 , -0.00423646, -0.11687607,  0.42869237,
       -0.20204553, -0.31456494, -0.27588758,  0.2633517 ,  0.38322195,
        0.21068761, -0.43524468, -0.3621421 , -0.13118613, -0.22107878,
        0.08333623,  0.16229126, -0.17648011, -0.44074973,  0.09028256,
        0.12995642, -0.06009729,  0.1622938 , -0.1013926 , -0.5386657 ,
        0.45121804, -0.01630789,  0.20510393, -0.5400061 ,  0.36

In [92]:
from tqdm import tqdm

In [93]:
X= []
for doc in tqdm(data['review'].values):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [11:00<00:00, 15.11it/s]


In [95]:
X=np.array(X)

In [96]:
X.shape

(9983, 100)

In [97]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y= encoder.fit_transform(data['sentiment'])

In [98]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [99]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=1)

In [100]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [101]:
mnb=GaussianNB()
mnb.fit(X_train, y_train)
y_pred=mnb.predict(X_test)
accuracy_score(y_test, y_pred)

0.7155733600400601